upstream django_api {
    server backend:8000;
}

upstream react_frontend {
    server frontend:4173;
}

server {
    listen 80;
    server_name _;

    location /api/ {
        proxy_pass http://django_api/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin/ {
        proxy_pass http://django_api/admin/;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://react_frontend;
        proxy_set_header Host $host;
    }
}
